url: http://www.cairnsjuicesanddrinks.com.au
baseurl: http://www.cairnsjuicesanddrinks.com.au

# Site settings
title: Cairns Juices and Drinks
email: cairnsjuicesanddrinks@gmail.com
description: "Cairns Juices and Drinks supplies top quality juices, drinks and beverages to Cairns and surrounding areas, Australia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ben Allen
  pic: 1
  position: Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
- name: Cath Allen
  pic: 2
  position: Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Blurgh
  - line: Another address blurcb

# Build settings
markdown: kramdown
permalink: pretty
